sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react-testing-image -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-testing-image npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-616520069289"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
