sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react-testing-image -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-testing-image npm run test -- --coverage
